version: '3.9'

services:
  app:
    image: trust-loans-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://app-db:27017/docker-node-app
      JWT_SECRET: my-secret # you can use any string
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    networks:
      - mongodb

networks:
  mongodb:
    driver: bridge

volumes:
  data:
